apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  connection-string: {{ printf "Host=postgres;Port=%v;Database=%s;Username=%s;Password=%s" .Values.postgres.port .Values.postgres.database .Values.postgres.username .Values.postgres.password | b64enc }}